### ISSUE TITLE
How to access GPT4 vocabulary

### ISSUE THREAD

**Issue by YuchenHui22314** [kaisugi/gpt4_vocab_list#1]
Hi! Thank you for the list! I am just wondering how you managed to access the GPT4 vocabulary, because I tried to use tiktoken but it is not well documented....

**Comment by kaisugi** [comment]
Hi!
I forgot the details, but the following links would be helpful

https://github.com/openai/tiktoken/blob/main/tiktoken_ext/openai_public.py#L64-L66
https://github.com/openai/tiktoken/blob/main/tiktoken/load.py#L121-L127

**Comment by YuchenHui22314** [comment]
Oh I see, thank you so much!
